[package]
name = "kfs-shell"
version = "0.1.0"
authors = ["roblabla <unfiltered@roblab.la>"]

[dependencies]
gif = { git = "https://github.com/roblabla/image-gif" }
font-rs = { git = "https://github.com/orycterope/font-rs" }
spin = { git = "https://github.com/Orycterope/spin-rs.git" }
hashmap_core = "0.1.9"
log = "0.4.2"
linked_list_allocator = "0.6.2"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.0.0"