[package]
name = "kfs-shell"
version = "0.1.0"
authors = ["roblabla <unfiltered@roblab.la>"]

[dependencies]
gif = { git = "https://github.com/roblabla/image-gif" }
font-rs = { git = "https://github.com/orycterope/font-rs" }
spin = "0.4"
hashmap_core = "0.1.9"
log = "0.4.2"
libuser = { path = "../libuser" }

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.0.0"
