language: rust
rust:
- nightly

# Install grub-mkrescue
addons:
  apt:
    packages:
    - grub-common
    - gcc-multilib

# Install cargo-make and rust-src rustup component
before_install:
- cargo install cargo-make || echo "cargo-make already installed"
- rustup component add rust-src || echo "rust-src already installed"
- rustup target install i686-unknown-linux-gnu || echo "target i686-unknown-linux-gnu already installed"

script:
- cargo make iso
- cargo make iso-release
- cargo make test
- cargo make doc-full

cache: cargo
