language: rust
rust:
- nightly

# Install grub-mkrescue
addons:
  apt:
    packages:
    - grub-common

# Install cargo-make and rust-src rustup component
before_install:
- cargo install cargo-make || echo "cargo-make already installed"
- rustup component add rust-src || echo "rust-src already installed"

script:
- cargo make iso
- cargo make iso-release
- cargo test

cache: cargo
