[package]
authors = ["roblabla <unfiltered@roblab.la>", "orycterope <tvermeilh@gmail.com>"]
name = "kfs"
version = "0.1.0"

[dependencies]
compiler_builtins = { git = "https://github.com/rust-lang-nursery/compiler-builtins", features = ['mem'] }
ascii = { version = "0.8.6", default-features = false }
lazy_static = { version = "1.0.0", features = ["spin_no_std"] }
spin = "0.4.6"
bit_field = "0.9.0"
arrayvec = { version = "0.4.7", default-features = false }
byteorder = { version = "1.2.1", default-features = false }
