[package]
authors = ["roblabla <unfiltered@roblab.la>"]
name = "kfs"
version = "0.1.0"

[dependencies]
compiler_builtins = { git = "https://github.com/rust-lang-nursery/compiler-builtins", features = ['mem'] }
