[env]
RUST_TARGET_PATH = "${PWD}"

[tasks.iso]
description = "Creates a bootable ISO containing the kernel and grub."
dependencies = ["xbuild"]
script = [
'''
cp target/i386-unknown-none/debug/kfs isofiles/boot/kernel.bin
grub-mkrescue -o os.iso isofiles
'''
]

[tasks.iso-release]
description = "Creates a bootable ISO containing the kernel and grub."
dependencies = ["xbuild-release"]
script = [
'''
cp target/i386-unknown-none/release/kfs isofiles/boot/kernel.bin
grub-mkrescue -o os.iso isofiles
'''
]

[tasks.xbuild]
description = "Runs the rust compiler."
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none", "--bin=kfs"]

[tasks.xbuild-release]
description = "Runs the rust compiler."
command = "cargo"
args = ["xbuild", "--target=i386-unknown-none", "--release", "--bin=kfs"]

[tasks.qemu]
description = "Runs the bootable ISO in qemu."
dependencies = ["iso-release"]
command = "qemu-system-i386"
args = ["-cdrom", "os.iso", "-serial", "stdio", "-vnc", ":0", "-no-reboot", "-enable-kvm"]

[tasks.qemu-debug]
description = "Runs the bootable ISO in qemu with gdb support"
dependencies = ["iso"]
command = "qemu-system-i386"
args = ["-cdrom", "os.iso", "-serial", "stdio", "-vnc", ":0", "-no-reboot", "-gdb", "tcp::9090", "-S", "-d", "int,cpu_reset"]

[tasks.doc]
description = "Document the kernel"
dependencies = ["xbuild"]
env = { "RUSTFLAGS" = "--sysroot=${PWD}/target/sysroot",  "RUSTDOCFLAGS" = "--sysroot=${PWD}/target/sysroot"}
command = "cargo"
args = ["rustdoc", "--target=i386-unknown-none", "--bin=kfs"]

[tasks.fulldoc]
description = "Document the kernel"
dependencies = ["xbuild"]
env = { "RUSTFLAGS" = "--sysroot=${PWD}/target/sysroot",  "RUSTDOCFLAGS" = "--sysroot=${PWD}/target/sysroot"}
command = "cargo"
args = ["rustdoc", "--target=i386-unknown-none", "--bin=kfs", "--", "--document-private-items"]
