[tasks.iso]
description = "Creates a bootable ISO containing the kernel and grub."
dependencies = ["xbuild"]
script = [
'''
cp target/i386-unknown-none/debug/kfs isofiles/boot/kernel.bin
grub-mkrescue -o os.iso isofiles
'''
]

[tasks.iso-release]
description = "Creates a bootable ISO containing the kernel and grub."
dependencies = ["xbuild-release"]
script = [
'''
cp target/i386-unknown-none/release/kfs isofiles/boot/kernel.bin
grub-mkrescue -o os.iso isofiles
'''
]

[tasks.xbuild]
description = "Runs the rust compiler."
script = [
'''
env RUST_TARGET_PATH=`pwd` cargo xbuild --target=i386-unknown-none --bin=kfs
'''
]

[tasks.xbuild-release]
description = "Runs the rust compiler."
script = [
'''
env RUST_TARGET_PATH=`pwd` cargo xbuild --release --target=i386-unknown-none --bin=kfs
'''
]

[tasks.qemu]
description = "Runs the bootable ISO in qemu."
dependencies = ["iso-release"]
command = "qemu-system-i386"
args = ["-cdrom", "os.iso", "-serial", "stdio", "-no-reboot", "-enable-kvm"]

[tasks.qemu-debug]
description = "Runs the bootable ISO in qemu."
dependencies = ["iso"]
command = "qemu-system-i386"
args = ["-cdrom", "os.iso", "-gdb", "tcp::9090", "-S", "-serial", "stdio", "-no-reboot", "-d", "int,cpu_reset"]

[tasks.qemu-vnc]
description = "Runs the bootable ISO in qemu in vnc mode."
dependencies = ["iso"]
command = "qemu-system-i386"
args = ["-cdrom", "os.iso", "-serial", "stdio", "-vnc", ":0"]

[tasks.vb]
description = "Fait tourner qemu sur le PC de l'animal bizarre"
script = [
'''
scp -r Makefile.toml Cargo.toml link.T i386-unknown-none.json src root@192.168.56.101:/root/workspace/kfs
ssh root@192.168.56.101 -t 'cd workspace/kfs ; exec ~/.cargo/bin/cargo make qemu-vnc'
''']
