[package]
name = "kfs-vi"
version = "0.1.0"
authors = ["roblabla <unfiltered@roblab.la>"]

[dependencies]
kfs-libuser = { path = "../libuser" }
kfs-libutils = { path = "../libutils" }
spin = "0.5"
hashmap_core = "0.1.9"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.2.0"