[package]
name = "kfs-libkern"
version = "0.1.0"
authors = ["roblabla <unfiltered@roblab.la>"]
license = "Apache-2.0 OR MIT"

[dependencies]
kfs-libutils = { path = "../libutils" }
bitflags = "1.0"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.2.0"
