[package]
name = "kfs-clock"
version = "0.1.0"
authors = ["roblabla <unfiltered@roblab.la>", "orycterope <tvermeilh@gmail.com>"]
license = "Apache-2.0 OR MIT"

[dependencies]
kfs-libuser = { path = "../libuser" }
